### ISSUE TITLE
Support HTTP requests using system CA bundle

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/python#178]
This issue was initially reported in the [Cloud Foundry Python Buildpack](https://github.com/cloudfoundry/python-buildpack/issues/195), but it probably makes sense to consider it in the Paketo Buildpack as well.

The request here would be for the buildpack to automatically set `export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` (perhaps only when the app uses the requests package?). This would allow Python apps to make HTTP requests using the system/operator defined CA certificate

**Comment by arjun024** [comment]
@kvedurmu  Looks like `requests` is not part of the Python Standard Library, and is a popular external library. Given this, should we instead just advice users to set their env vars in `<appdir>/.profile`?

**Comment by kvedurmu** [comment]
Yeah, the idea would be the env var is only set when the requests package is in the requirements.txt file. That said, I don't have any strong opinions here.

**Comment by fg-j** [comment]
It's been a little while since the last activity on this issue. @paketo-buildpacks/python-maintainers, is this still a relevant feature?

**Comment by robdimsdale** [comment]
I haven't heard any recent feedback indicating this is something we should solve, so I'm going to close this issue. We can re-open if/when we get more evidence that this feature would be valuable.

**Comment by benjie91** [comment]
I was using Procfile to specify the startup command and I realised that setting BPE_DEFAULT_REQUESTS_CA_BUNDLE does not set the environment variable and thus my requests to external URL fails. Any documentation on how this should be done?

The only workaround that I think might work but I have not tested yet is to use launcher command instead of the Procfile method.
