### ISSUE TITLE
Feature request: support poetry package manager

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/python#196]
This issue is a placeholder for an issue in an archived repository.

[Issue](https://github.com/cloudfoundry/python-cnb/issues/4)

**Comment by cwlbraa** [comment]
I recently started using poetry and it's pretty dramatic how much nicer it is than pipenv. It's also much easier to manage virtualenvs with it without plugins or other weirdness. It does have the ability to `poetry export -o requirements.txt` which is a decent workaround to make it mostly pip-buildpack compatible.

**Comment by xobtoor** [comment]
I would also vote for poetry support, because we switched completly to poetry for all python projects.

**Comment by robdimsdale** [comment]
Poetry support is underway! We have opened #407 to track the work, and [RFC 0006](https://github.com/paketo-buildpacks/rfcs/blob/main/text/python/0006-poetry.md) has more details about the high-level goals.

I'll close this issue in favor of the tracking issue.
