### ISSUE TITLE
Add support for pyspark

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/python#197]
This issue is a placeholder for an issue in an archived repository.

[Issue](https://github.com/cloudfoundry/python-cnb/issues/2)

**Comment by robdimsdale** [comment]
@ansergit given you opened the original issue nearly 2 years ago, is adding pyspack support still relevant to you?

**Comment by robdimsdale** [comment]
I'm going to close this issue due to lack of activity. Please feel free to re-open if there is an interest in exploring pyspark.

For future reference, while I think the paketo architecture would make it easier to create a buildpack for pyspark (as it appears to require python and java) I am not yet convinced it makes sense for the paketo team to maintain this or include it in the top-level python buildpack. I think it would be better for someone closer to the problem domain (and who will actually use the buildpack) to create and maintain it.

**Comment by Whazor** [comment]
As someone who is involved in the data science domain, I agree with reasoning for closing the issue. Spark is big and heavily reliant on Java. It would also require some knowledge on how users are using Spark.

In that sense Spark would normally not be top-layer but run by something else: like Jupyter Notebooks, a scheduler service, a bigger production system so there would normally be a layer on top of Spark as well.

Having said that, buildpacks for data science are cool and Spark as a buildpack layer would make sense. It would be using other buildpacks from Paketo and use several existing buildpacks. But it would need the complete picture and a separate community effort to lead it, which could be outside or inside Paketo and indeed building on top of existing Paketo buildpacks and tooling.

**Comment by robdimsdale** [comment]
@Whazor thanks for sharing your thoughts! It's helpful to get feedback from users who are more familiar with the pyspark use-case, and it's validating to hear that we're on the same page in terms of the scope of a pyspark buildpack and where the responsibility for it would lie.

It sounds like pyspark is a good candidate for a buildpack, and that it would be composed of `python` and `java` buildpacks (and possibly others), and that the output of the build process would be a correctly-configured pyspark installation. This could then be used by other applications like Jupyter Notebooks, or even depended on by other buildpacks.

So, from a python perspective, it sounds like there's not a lot of action we can take at the moment. If you end up exploring pyspark, please reach out if you find the python buildpack doesn't meet your needs and we can identify ways to ensure the python buildpack works for you.
