### ISSUE TITLE
Add quick example usage to the readme

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/python#318]
It would be nice to have a short section in the README that showed  a very basic example of how to use the buildpack. Just the basic pack command and the dependencies so this language family buildpack could be promoted to the python community without folks having to read a lot of other docs.

**Comment by arjun024** [comment]
@andymoe Hopefully soon https://github.com/paketo-buildpacks/rfcs/pull/91 will pass and we can publish docs on the paketo website and samples in the samples repo

**Comment by arjun024** [comment]
It's available in [samples](https://github.com/paketo-buildpacks/python/tree/main/samples) now

**Comment by robdimsdale** [comment]
I added a link to the docs from the README - see https://github.com/paketo-buildpacks/python/pull/410

@andymoe does that work for you? It's consistent with other buildpack READMEs - adding a link without duplicating usage in the README.

**Comment by robdimsdale** [comment]
I'll close this now that #410 is merged. Feel free to re-open if you don't think this is sufficient.
