### ISSUE TITLE
Custom build commands

### ISSUE THREAD

**Issue by chriddyp** [paketo-buildpacks/python#355]
Hi! Love this project ✨ 

How do folks recommend running custom install / build commands? For example, to use the `pyodbc` package, you need to copy some files into a particular directory.

When using tools like `dokku`, I've used their custom ["predeploy" hook ](https://dokku.com/docs/advanced-usage/deployment-tasks/) that would run a script like:

```
ACCEPT_EULA=Y dpkg -i msodbcsql17_17.6.1.1-1_amd64.deb

cp odbc.ini /etc/odbc.ini
cp odbcinst.ini /etc/odbcinst.ini
```

Where `odbc.ini` are included in the application structure.

There are three main use cases:
1. Copying files around to configure Python packages with Linux drivers. Many database packages require this.
2. Downloading large data files into the image during build, rather than keeping the data in the repository itself
3. Warming up a cache on deploy

**Comment by chriddyp** [comment]
Other solutions I've seen include creating a custom buildpack that runs arbitrary commands, like [`heroku-buildpack-run`](https://github.com/weibeld/heroku-buildpack-run)

**Comment by arjun024** [comment]
Hi @chriddyp, If you want to run custom commands, you'll have to use one of those custom command buildpacks or create your buildpack.

**Comment by arjun024** [comment]
@chriddyp There's not one AFAIK. You can create one. I have [a personal buildpack](https://github.com/arjun024/build-cmd-cnb) (not prod quality) I use for test purposes if want to checkout.

If you're interested to create a proposal/implementation for such a utility buildpack, checkout https://github.com/paketo-buildpacks/rfcs. Contributors frequently propose new buildpacks to the project

**Comment by robdimsdale** [comment]
Hey @chriddyp did the suggestion above answer your question? Supporting custom pre-processing commands is outside of the scope of the python buildpack. I'm going to close this issue but please feel free to re-open it if you have further questions.
