### ISSUE TITLE
Evaluate adding support for alternative python implementations

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/python#414]
We should consider whether it is valuable to support alternative python implementations (i.e. alternatives to `cpython`). There is a list [here](https://www.python.org/download/alternatives/); some of which are built on an alternative runtime (e.g. Java, .NET) and some of which are standalone.

The most obvious choice to explore is [pypy](https://www.pypy.org/), as it is similar to `cpython` in that it has no external dependencies and is aimed at web applications (vs other implementations like micropython which is aimed at microcontrollers).

It might be worth tracking the mechanism for switching between Java application servers (e.g. Tomcat and Liberty) in https://github.com/paketo-buildpacks/rfcs/pull/145. Whatever interface is decided upon might be a good basis for switching between alternative `python` implementations.

**Comment by joshuatcasey** [comment]
I recommend we continue to only support `cpython`.

I can't find any data to justify that it's valuable to add an alternative python implementation such as `pypy`. I went looking for:

- Issues in the `paketo-buildpacks` org: https://github.com/search?q=org%3Apaketo-buildpacks+pypy&type=issues
- Issues in the `paketo-community` org: https://github.com/search?q=org%3Apaketo-community+pypy&type=issues
- Conversations on the Paketo slack (#python or other channels, note that deep linking to a search is not possible): https://paketobuildpacks.slack.com/archives/CUD6UTCJW
- Google: https://www.google.com/search?q=%22paketo%22+%22pypy%22, which yielded only one result as of the time of writing: https://github.com/paketo-buildpacks/feedback/discussions/2#discussioncomment-282787 (no upvotes on the suggestion).

I also tried to research which python implementations were of most value to the python community, and was hoping to find some sort of popularity index for the various implementations (`cpython`, `pypy`, `IronPython`, `Jython`, etc). I found no quantitative data, although various blog posts listing the different implementations usually said something to the effect that `cpython` is the clear leader in the field.

Note: This research was only about the popularity or market share of the implementations, not the technical pros and cons.

- https://trends.google.com/trends/explore?date=today%205-y&q=cpython,pypy. Interestingly, the trendlines are really close. Add "python" to the trendline and it's multiple orders of magnitude above either `cpython` or `pypy`, so I suspect we're seeing noise and not signal.
- Stackoverflow Trends does not have `cpython` or `pypy` available as indexed tags for comparison, although Python clearly [has the most tags in recent years](https://insights.stackoverflow.com/trends?tags=java%2Cc%2Cc%2B%2B%2Cpython%2Cc%23%2Cvb.net%2Cjavascript%2Cassembly%2Cphp%2Cperl%2Cruby%2Cvb%2Cswift%2Cr%2Cobjective-c)
- "[CPython is] the most common implementation" https://www.toptal.com/python/why-are-there-so-many-pythons
- "CPython is the reference implementation of Python" https://en.wikipedia.org/wiki/Python_(programming_language)#Implementations
- "[CPython] is the most popular Python implementation and is used by the vast majority of Python developers" https://cloudbytes.dev/snippets/which-python-implementation-you-should-use-cpython-pypy-etc

**Comment by robdimsdale** [comment]
Thanks @joshuatcasey! This is fantastic research.

I agree with your recommendation that we continue to support only `cpython`.

**Comment by robdimsdale** [comment]
Agreed. Technically I suspect it would be somewhere between easy and moderately-difficult to support another implementation of python. But I don't want to do that if there's no value in it.
