### ISSUE TITLE
Implement RFC0041: Use Direct Processes and exec.d

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/python#464]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0041-direct.md)

## Summary

All Paketo buildpacks language families must update their buildpacks to use direct process types. There is an upstream change that will only permit direct process types.

Buildpack authors need to review buildpacks and take the following actions:

- Look for the usage of profile.d scripts and convert them to exec.d binaries
- Update any buildpacks that write process types and set `direct: true`. While doing this, evaluate the command being generated and determine if it requires a shell. If it can be done without a shell, make that change. If it requires a shell, you will need to wrap the original command with a call to the shell. For example: `bash -c '<cmd>'` (or some other shell). Please note that requiring a shell prohibits the buildpack from running in environments like tiny where there is no shell available.
- Investigate if users of the buildpack are likely to use `.profile` scripts. These will no longer be supported after switching to the direct process type. If this is common for buildpack users, then document that `.profile` is no longer supported and document the actions one could take to replace that script (like using procfile or environment-variables buildpacks). Buildpack language families may choose to wait if this is deemed a major impact to users until there is an acceptable solution (such as a profile buildpack).

## Sub-Issues
* [x] https://github.com/paketo-buildpacks/python-start/issues/138
* [x] https://github.com/paketo-buildpacks/poetry-run/issues/37

**Comment by robdimsdale** [comment]
This is complete. Closing.
