### ISSUE TITLE
Support Jammy Jellyfish

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/python#490]
## Describe the Enhancement

Ultimately, we want to be able to build Python apps on top of the Paketo Jammy stacks. Currently, builds fail because buildpacks like `cpython` don't have the Jammy stack listed in their supported stacks.

## Possible Solution

- Update `buildpack.toml` and dependencies to add `io.buildpacks.stacks.jammy` as a compatible stack
- (If necessary) Recompile installed dependencies to work on Jammy 
- Add some integration tests that test the buildpack against Jammy

## Language Family Buildpacks
- [x] [conda-env-update](https://github.com/paketo-buildpacks/conda-env-update)
  - [x] https://github.com/paketo-buildpacks/conda-env-update/pull/142
- [x] [cpython](https://github.com/paketo-buildpacks/cpython)
  - [x] https://github.com/paketo-buildpacks/cpython/pull/360
  - [x] https://github.com/paketo-buildpacks/dep-server/pull/189
- [x] [miniconda](https://github.com/paketo-buildpacks/miniconda)
  - [x] https://github.com/paketo-buildpacks/miniconda/pull/228
- [x] [pip](https://github.com/paketo-buildpacks/pip)
  - [x] https://github.com/paketo-buildpacks/pip/pull/272
- [x] [pip-install](https://github.com/paketo-buildpacks/pip-install)
  - [x] https://github.com/paketo-buildpacks/pip-install/pull/138
- [x] [pipenv](https://github.com/paketo-buildpacks/pipenv)
  - [x] https://github.com/paketo-buildpacks/pipenv/pull/244
- [x] [pipenv-install](https://github.com/paketo-buildpacks/pipenv-install)
  - [x] https://github.com/paketo-buildpacks/pipenv-install/pull/136
- [x] [poetry](https://github.com/paketo-buildpacks/poetry)
  - [x] https://github.com/paketo-buildpacks/poetry/pull/69
- [x] [poetry-install](https://github.com/paketo-buildpacks/poetry-install)
  - [x] https://github.com/paketo-buildpacks/poetry-install/pull/51
- [x] [poetry-run](https://github.com/paketo-buildpacks/poetry-run)
  - [x] https://github.com/paketo-buildpacks/poetry-run/pull/52
- [x] [python-start](https://github.com/paketo-buildpacks/python-start)
  - [x] https://github.com/paketo-buildpacks/python-start/pull/152

## Utility Buildpacks
- [x] [procfile](https://github.com/paketo-buildpacks/procfile/blob/f921152f681e25953eb2e2103e97e91d280dd5c1/buildpack.toml#L34-L35)
- [x] [environment-variables](https://github.com/paketo-buildpacks/environment-variables/blob/c0dde7cdd04775f4efe600f69fd949951de922bb/buildpack.toml#L34-L41)
- [x] [ca-certificates](https://github.com/paketo-buildpacks/ca-certificates/blob/ecc4d9c8af02d3177f158b1ed82f881bb51d6990/buildpack.toml#L53-L60)
- [x] [image-labels](https://github.com/paketo-buildpacks/image-labels/blob/ad98a9710c61106110412967eb11a211672e54a9/buildpack.toml#L99-L106)
- [x] [watchexec](https://github.com/paketo-buildpacks/watchexec/blob/f1af9c1891269cfa4b82741d7e4c79d444b0d036/buildpack.toml#L48-L55)

## Motivation

Part of https://github.com/paketo-buildpacks/builder-jammy-base/issues/1

**Comment by joshuatcasey** [comment]
✅  Jammy support included in `2.0.0`: https://github.com/paketo-buildpacks/python/releases/tag/v2.0.0
